### ISSUE TITLE
x86 binary doesn't have assembler optimizations

### ISSUE THREAD

**Issue by Javernaut** [Javernaut/ffmpeg-android-maker#1]
The configuration for x86 binary explicitly disables assembler optimizations, since they bring text relocations. This stuff is forbidden in the latest versions of Android OS.

So it should be investigated further and ideally those optimizations should be enabled back with dropping of text relocations themselves.

**Comment by batousik** [comment]
Just ran into text relocations issue, uncommenting disable network support somehow added text relocations to libavcodec

**Comment by Javernaut** [comment]
@batousik In my experience with this library, exactly assembler optimizations for x86 target produces binaries with text relocations. I have even just checked myself, that if you only enable 'network' module, the x86 binary will be ok. Please check if you accidentally enabled assembler optimizations for  this target.
You can check you binaries with the readelf tool as is explained [here](https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md).
If you use Android emulator, I suggest using x86_64 version of it, because such problem just doesn't take place (even with 'network' module).
If you still have this problem, show me the scrip you are using for compilation and the way you get this error.

**Comment by Javernaut** [comment]
@batousik I've tuned the script to generate files with the information about text relocation presence in all binaries that are generated. The file stats/text-relocations.txt now has this info. Just check the file after the script invocation. Thus you will know the problem presence right after the FFmpeg compilation.

**Comment by batousik** [comment]
@Javernaut thanks a lot, i must have been doing more than just uncommenting network, only uncommenting network produced a valid binary.  text relocation is just another nightmare for someone who just started C

**Comment by Javernaut** [comment]
Even the latest 4.2 and master branches of FFmpeg still has text relocations. This ~~issue~~ feature takes place in FFmpeg itself [for a long time](https://trac.ffmpeg.org/ticket/4928). It will take a significant effort to rewrite certain FFmpeg modules to drop Text Relocations completely. So for now I'm ok with just disabling of assembler optimizations for x86 binary at all.
