### ISSUE TITLE
Support building libsoxr

### ISSUE THREAD

**Issue by Kyant0** [Javernaut/ffmpeg-android-maker#102]
https://github.com/chirlu/soxr

**Comment by Javernaut** [comment]
@Kyant0 
https://github.com/Javernaut/ffmpeg-android-maker/wiki/External-libraries-integration

**Comment by Kyant0** [comment]
But it said "cmake: not found" in the ./in, I don't know how to build it

**Comment by Kyant0** [comment]
Oh, I fixed it. I changed cmake version in the script, but haven't changed it at other places.
