### ISSUE TITLE
libavcoded.so being only 24 bytes ?

### ISSUE THREAD

**Issue by FcTD4mN** [Javernaut/ffmpeg-android-maker#105]
Hello, 
I'm trying to build FFMPEG for android and use the generated shared libraries to then build a side library.

I did use your script with no parameters: it did download ffmpeg 7.1, and then build everything with no visible error.
At the end, i do see everything in the output directory, but looking at libavcodec.so as well as libavformat.so, they are only 24 bytes in size, which seems odd.

To test and compare, I downloaded prebuilt versions of those .so libraries. 
They are, as well as the .dylib that i built for macOS, around 12MB.

When linking these .so to my side lib, I end up with an "unkown file type" ld.lld error.
The prebuilt versions do work fine.

Do you have any idea of what could be the issue here ? 
Is there a config parameter that i'm missing ?

**Comment by Javernaut** [comment]
Interesting, never faced such an issue.

Have you modified any script anyhow? Or just executed the `./ffmpeg-android-maker.sh` right after the clone?

What OS and NDK version did you use?

Have you tried to, well, execute the script again?

I've just tried building it on macos and the results are pretty usual:

<img width="248" alt="image" src="https://github.com/user-attachments/assets/6a765b41-8813-4851-95c1-f0ca1d9f22f6">
