### ISSUE TITLE
Compilation on Windows - Issues 

### ISSUE THREAD

**Issue by Consti10** [Javernaut/ffmpeg-android-maker#11]
Hello,
The info how to compile on windows is a bit sparse, here is what I did:
a) Install msys2
b) Open the msys2 console and update first,
pacman -Syu
then install the mentioned libraries:
pacman -S make git diffutils tar
c) change directory to where you cloned the ffmpge-android-maker, e.g.
cd /c/mydir
d) execute the script via 
./ffmpeg-android-maker.sh

When doing so, the script runs for ~1 min and then fails with
/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi16-clang is unable to create an executable file.
C compiler test failed.

It creates
output\lib\armeabi-v7a
folder but nothing is in it.

**Comment by Javernaut** [comment]
Hello @Consti10.

According to the error message you didn't define the ANDROID_NDK_HOME environment variable. Note that you should do it in Msys itself.

**Comment by Consti10** [comment]
Thanks javernaut, I am not the first one to ask that question I see now -will report back.

**Comment by Consti10** [comment]
can you give me a short explanation how to set the path in msys ?
I know how to set it in Windows -> Edit the system variables
But that doesn't seem to work

**Comment by Consti10** [comment]
when executed inside msys,
echo $ANDROID_NDK_HOME
returns
C:\Users\Consti10\AppData\Local\Android\Sdk\ndk-bundle
This is the place where I have the ndk installed (e.g. ndk-build.cmd resides there)

**Comment by Javernaut** [comment]
You need to use Unix path to your NDK like this:
![image](https://user-images.githubusercontent.com/979018/64700231-2e243180-d4af-11e9-9842-693fafb51cf2.png)

**Comment by Javernaut** [comment]
Try to define the variable like this:

`export ANDROID_NDK_HOME=c/Users/Consti10/AppData/Local/Android/Sdk/ndk-bundle`

**Comment by Consti10** [comment]
Hello, I left it running with the _double-backslash in windows_ method until the end - it spilled a lot more errors similar to the one above and did not create anything in the folders - it only created the
lib -> arm64-v8a , x86, x86_64 usw folder structure.

I'l try again

**Comment by Javernaut** [comment]
By the way, you will need to export the same variable each time you open MSYS app.

But you can edit your startup script like I did below:

![image](https://user-images.githubusercontent.com/979018/64702914-1ac79500-d4b4-11e9-83dd-5f7b1725a176.png)

Check out the file location. I use ZSH as my shell, so the startup script file is `.zshrc`. If you use standard bash, refer to this [link](https://superuser.com/questions/405342/mingw-bash-profile) for more details.

**Comment by Consti10** [comment]
I also ran the WhatTheCodec example app - worked.

**Comment by Javernaut** [comment]
Great!

Yeah, building libraries for all 4 ABIs is quite time consuming. On Travis CI it takes ~30 minutes. And it takes only **4** minutes for a Macbook Pro 2019 with i9 processor. My point is that the hardware matters when it comes to C library compilation. Or you can build only one necessary architecture if you run debug builds, for example. I explained it [here](https://github.com/Javernaut/ffmpeg-android-maker/issues/9#issuecomment-529536103).

Enjoy, you have done everything right!
