### ISSUE TITLE
ffmpeg with mp3 codec

### ISSUE THREAD

**Issue by Exeu** [Javernaut/ffmpeg-android-maker#12]
Hello!
Thanks for this script. Im desperate trying to build ffmpeg for android. so far i can build a naked instance now with our script. But i need to add lame (mp3) to it because i need to decode MPEG2-L2 streams.

im running the script and added --enable-libmp3lame to the configure part.
when im trying to build this now it shows the following:

`ERROR: libmp3lame >= 3.98.3 not found`

On my system i installed lame:
`janeichhorn@Jans-MBP sources % lame
LAME 64bits version 3.99.5 (http://lame.sf.net)`

also it seems like the libs are placed in the correct directories:

for lib: 

`janeichhorn@Jans-MBP sources % ls /usr/local/lib/libmp3lame.a
/usr/local/lib/libmp3lame.a`

for include:

`
janeichhorn@Jans-MBP include % ls /usr/local/include/lame
lame.h
`

Also i added 
`    --extra-cflags="-I/usr/local/include -O3 -fPIC" \
    --extra-ldflags="-L/usr/local/lib" \`

do you know or does anyone knows how this is working? I am using mac OSX 10.15.1.

this is the output of the build log:

`test_ld cc -lmp3lame -lm
test_cc
BEGIN /var/folders/p_/yz6grx197198g3q41x22hxk40000gn/T//ffconf.B1MgsdwI/test.c
    1	#include <lame/lame.h>
    2	#include <stdint.h>
    3	long check_lame_set_VBR_quality(void) { return (long) lame_set_VBR_quality; }
    4	int main(void) { int ret = 0;
    5	 ret |= ((intptr_t)check_lame_set_VBR_quality) & 0xFFFF;
    6	return ret; }
END /var/folders/p_/yz6grx197198g3q41x22hxk40000gn/T//ffconf.B1MgsdwI/test.c
/Users/janeichhorn/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang --sysroot=/Users/janeichhorn/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Dstrtod=avpriv_strtod -DPIC -I/usr/local/include -O3 -fPIC -march=armv7-a -std=c11 -fPIE -fomit-frame-pointer -fPIC -marm -c -o /var/folders/p_/yz6grx197198g3q41x22hxk40000gn/T//ffconf.B1MgsdwI/test.o /var/folders/p_/yz6grx197198g3q41x22hxk40000gn/T//ffconf.B1MgsdwI/test.c
/Users/janeichhorn/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang -L/usr/local/lib --sysroot=/Users/janeichhorn/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -march=armv7-a -Wl,--as-needed -Wl,-z,noexecstack -fPIE -pie -o /var/folders/p_/yz6grx197198g3q41x22hxk40000gn/T//ffconf.B1MgsdwI/test /var/folders/p_/yz6grx197198g3q41x22hxk40000gn/T//ffconf.B1MgsdwI/test.o -lmp3lame -lm
/Users/janeichhorn/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: mp3lame: no archive symbol table (run ranlib)
/var/folders/p_/yz6grx197198g3q41x22hxk40000gn/T//ffconf.B1MgsdwI/test.o:test.c:function check_lame_set_VBR_quality: error: undefined reference to 'lame_set_VBR_quality'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: libmp3lame >= 3.98.3 not found`

Would be so nice if someone can help me out here.

**Comment by Javernaut** [comment]
Hello @Exeu ,

I didn't try to add any separate library so far, because I didn't have a necessity doing so.

Regarding your particular case I have a couple of ideas:

1) As you 'installed' the libmp3lame into your system, it means that you have only x86 or x86_64 version of the library. I think you either need all 4 precompiled versions of the libmp3lame, or its source code.

2) Not sure about his one: perhaps you have problems with your pkg-config script. I just don't have one, as I don't need to resolve any external library.

I can try do it myself in nearest 2-3 days. 
Meanwhile, could you please share the script that you use now? Could you please upload it to your fork?

**Comment by Exeu** [comment]
Hey @Javernaut!
Thanks for the ultra fast response :)

It would be awesome if you can try it also. Meanwhile i will continue trying as well.

Attached the script im now using.

[ffmpeg-android-maker.txt](https://github.com/Javernaut/ffmpeg-android-maker/files/3826255/ffmpeg-android-maker.txt)

**Comment by Javernaut** [comment]
Hi @Exeu ,

I managed to compile FFmpeg with mp3lame library for all 4 architectures.

Your exact problem was that you used just the mp3lame that you installed into your host machine, but the thing is that static libraries of mp3lame for each of 4 architectures have to be provided separately for FFmpeg.

So I created a similar script lame-maker.sh to download the source code of mp3lame and compile it. Check the [with_lame](https://github.com/Javernaut/ffmpeg-android-maker/tree/with_lame) branch.

You just need to execute the same ffmpeg-android-maker.sh script, as I modified it to execute lame-maker.sh under the hood. This 2 scripts have a lot of duplications, as I was focussed on making the thing work in the first place.

For exact changes that I've done you can check [this commit](https://github.com/Javernaut/ffmpeg-android-maker/commit/c0b5c1ddfd0584581f5fffbe9c3de4522026392d) out.

One more thing. I only made the FFmped + mp3lame compilable. I can't guarantee it works properly, as I don't have a use case to implement. So there is a possibility you will have to tune the build script a little.

Cheers!

**Comment by Exeu** [comment]
WOW! Thanks man ! I will try this out asap and let you know if it worked out!

**Comment by Javernaut** [comment]
Hi @Exeu

Any luck so far?

**Comment by Exeu** [comment]
Sorry about the late feedback! Yes it works quite good.
Was exactly that problem of different achritectures..

Thanks for adding this feature to your Repo man :)
