### ISSUE TITLE
ffmpeg binary not getting built

### ISSUE THREAD

**Issue by acespring78** [Javernaut/ffmpeg-android-maker#13]
Hello! First off thanks for this great project!  I tried running the script so I can build the `ffmpeg` binary for android, however it doesn't appear that is getting generated. I modified the `configure` settings by removing the `--disable-programs` and disabled the other binaries I'm not interested in such as `ffprobe` and `ffplay`. In fact, this is what the modified `configure` options look like inside `ffmpeg-android-maker.sh`

```
  ./configure \
    --prefix=${BUILD_DIR}/${ABI} \
    --enable-cross-compile \
    --target-os=android \
    --arch=${TARGET_TRIPLE_MACHINE_BINUTILS} \
    --sysroot=${SYSROOT} \
    --cross-prefix=${CROSS_PREFIX} \
    --cc=${CC} \
    --extra-cflags="-O3 -fPIC" \
    --enable-shared \
    --disable-static \
    ${EXTRA_BUILD_CONFIGURATION_FLAGS} \
    --disable-runtime-cpudetect \
    --disable-ffplay \
    --disable-ffprobe \
    --disable-avdevice \
    --disable-postproc \
    --disable-swresample \
    --disable-avfilter \
    --disable-doc \
    --disable-debug \
    --disable-pthreads \
    --disable-network \
    --disable-bsfs
```

Any reason?

**Comment by acespring78** [comment]
Made a small modification and removed the `--disable-ffplay` and `--disable-ffprobe` from my example above and noticed that only `ffprobe` bin was created, but no `ffmpeg`:

(updated configure from above)
```
  ./configure \
    --prefix=${BUILD_DIR}/${ABI} \
    --enable-cross-compile \
    --target-os=android \
    --arch=${TARGET_TRIPLE_MACHINE_BINUTILS} \
    --sysroot=${SYSROOT} \
    --cross-prefix=${CROSS_PREFIX} \
    --cc=${CC} \
    --extra-cflags="-O3 -fPIC" \
    --enable-shared \
    --disable-static \
    ${EXTRA_BUILD_CONFIGURATION_FLAGS} \
    --disable-runtime-cpudetect \
    --disable-avdevice \
    --disable-postproc \
    --disable-swresample \
    --disable-avfilter \
    --disable-doc \
    --disable-debug \
    --disable-pthreads \
    --disable-network \
    --disable-bsfs
```

**Comment by acespring78** [comment]
Hmm, looks like after deleting all the options below `${EXTRA_BUILD_CONFIGURATION_FLAGS}`, I see the `ffmpeg` binary getting built inside the `build` folder.

**Comment by Javernaut** [comment]
Hello @acespring78 , thanks for kind words.

As for your issue, I've noticed that in configure script of the FFmpeg itself there is a line:

```ffmpeg_deps="avcodec avfilter avformat"```

which means that `avcodec`, `avfilter` and `avformat` are necessary for building the ffmpeg binary. In my script the `avfilter` is disabled. So by removing the

```--disable-avfilter```

you can achieve ffmpeg binary building. Keep `--disable-ffprobe` and `--disable-ffplay` though.

I've just tested it for armv7.

**Comment by acespring78** [comment]
Thanks for the quick reply @Javernaut ! Confirmed it works after following your suggestion.  This is a great tool and thanks for your help!
