### ISSUE TITLE
Question / Feature request h264_mediacodec

### ISSUE THREAD

**Issue by Consti10** [Javernaut/ffmpeg-android-maker#16]
Hello,
Why are you not using the android hw decoder in your example ? 
Will the build script also work with 
--enable-decoder=h264_mediacodec ?

**Comment by Javernaut** [comment]
Hello @Consti10,

I didn't try this flag yet, but it is in my todo list.

I'm currently working on other things in the Android project.

**Comment by Javernaut** [comment]
I transfered this issue to the private jira.
