### ISSUE TITLE
c compiler test failed

### ISSUE THREAD

**Issue by rakesh-mohan** [Javernaut/ffmpeg-android-maker#17]
> WARNING: /toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android-pkg-config not found, library detection may fail.
> mktemp -u XXXXXX
> A0Quav
> test_ld cc
> test_cc
> BEGIN /var/folders/gq/s_z1gl311m35t0lfbpd88h59yz5bw5/T//ffconf.OX3pcfIE/test.c
>     1	int main(void){ return 0; }
> END /var/folders/gq/s_z1gl311m35t0lfbpd88h59yz5bw5/T//ffconf.OX3pcfIE/test.c
> /toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang --sysroot=/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -O3 -fPIC -I/Users/rakesh-3121/repositories/ffmpeg-samples/ffmpeg-android-maker/build/external/arm64-v8a/include -c -o /var/folders/gq/s_z1gl311m35t0lfbpd88h59yz5bw5/T//ffconf.OX3pcfIE/test.o /var/folders/gq/s_z1gl311m35t0lfbpd88h59yz5bw5/T//ffconf.OX3pcfIE/test.c
> ./configure: line 974: /toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang: No such file or directory
> C compiler test failed.

Any help on this error

**Comment by Javernaut** [comment]
Hi @rakesh-mohan ,

I see you didn't define environment variables as it is described in [Prerequisites](https://github.com/Javernaut/ffmpeg-android-maker#prerequisites) section. Do it and run the scrip again.

**Comment by Javernaut** [comment]
@rakesh-mohan is everything ok now?

**Comment by rakesh-mohan** [comment]
@Javernaut Yeah! It works. Thanks for the quick help :)
