### ISSUE TITLE
Question / Feature - download files from Travis CI

### ISSUE THREAD

**Issue by Consti10** [Javernaut/ffmpeg-android-maker#18]
First, the Travis CI integration works fine on branches, too - I just had to do a 'dummy commit & push' as already described. Great !

However, I was wondering if it is possible to download the files generated by Travis Ci ? E.g. the .so and header files.

**Comment by Javernaut** [comment]
Hi @Consti10 ,

There are 3 things I need say.

1) First of all, as far as I know the Travis CI only 'does a thing' without saving any files for the later usage.

2) I personally don't think that *.so and *.h files are not the things you actually need from a CI. You better have an android library module that is assembled by Gradle into a singe AAR file (Android archive). I presume such a library will have JNI bindings and will completely hide FFmpeg as an implementation detail. The only one *.aar file is easier to manage. 
Then you can upload it to some (probably private) maven repo or just a cloud storage on your own. Using Gradle here will also allow you to use Gradle plugins for doing this actions less manually.
You can achieve this thing by making another repo with such an android library just like I did my [WhatTheCodec](https://github.com/Javernaut/WhatTheCodec), but only with Android library module.

3) Another thing is more like an advice. Do not put your credentials or any kind of private data (like even urls to the actual hosting) to the Travis CI configuration file. Use Travis CI's encryption features. Check its documentation for additional info.

**Comment by Consti10** [comment]
Hello,
I am using ffmpeg-android-maker just like you do in whatthecodec - build the .so / .h files and then include them manually such that I can link my native code with ffmpeg. 
[Project](https://github.com/Consti10/LiveVideo10ms)

Unfortunately the last time I built was with MinGW which is not supported anymore. So I tried it on Ubuntu with sdk/ndk installed via 'android studio' but no success so far.

So I was hoping to use Travis CI for that, since there it works.

**Comment by Javernaut** [comment]
My recent enhancement dropped Windows support, that is right. I just don't have enough time to make it work again (but I think it is possible).

Just as simple solution you can just zip the output directory and upload it to some kind of Dropbox or Google Drive, for example. But again, be sure you don't expose your credentials.

As for Ubuntu - the ffmpeg-android-maker should work there fine. And the Android Studio isn't actually necessary. You just need Android SDK and standard things like 'make' and other tools if you wish to build external libraries.

**Comment by Javernaut** [comment]
After some time thinking about the idea of downloading the result files from Travis CI I came up with certain ideas:

1) The Travis CI itself is only an implementation detail of CI for this project. Someone can use other CI services instead, so any implementation of getting files from Travis CI more likely will not work for other CI services.
2) CI tool is optional and it isn't focussed on some specific Android app.
3) Different users may want to upload such files to different places and featuring only one such way (like Dropbox, for example) doesn't solve the problem completely. Support for many such ways isn't the goal of this repo at all.

Considering this I do not have any plans for implementing such functionality and this should be the thing users may want to implement themselves. Now I'm clear on this issue.
