### ISSUE TITLE
c compiler test failed

### ISSUE THREAD

**Issue by Consti10** [Javernaut/ffmpeg-android-maker#19]
#17 

Hello,
I am using Ubuntu 19.10 in a VM and cannot get the build script to work.

I have installed android studio, then using the sdk manager from android studio I installed the ndk and cmake.
After that, I set the environment variables like this:
export ANDROID_SDK_HOME=$HOME/android-sdk and
export ANDROID_NDK_HOME=$ANDROID_SDK_HOME/ndk/21.0.6113669

Both folders exist. E.g. ANDROID_NDK_HOME contains the ndk-build.sh file and more.

However, when executing the script I get 
```
Building the component: ffmpeg
/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android16-clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
```

I also tried executing the commands from the travis.yml file one after another but It crashes in
`installAndroidComponent "ndk;21.0.6113669"` with an error that seems to link to the wrong jdk (which is 9 on ubuntu 19.10, and in the travis.yml it says jdk8 explicitly)

Any ideas ?

**Comment by Consti10** [comment]
My sdk folder looks like this:
![Capture1](https://user-images.githubusercontent.com/16462285/72999182-49a92c80-3dff-11ea-80c8-dbbdfcfee70b.PNG)

And the ndk looks like this:
![Capture2](https://user-images.githubusercontent.com/16462285/72999216-5463c180-3dff-11ea-9267-f9e3a7665bdb.PNG)

**Comment by Javernaut** [comment]
Android SDK doesn't work with Java 9 and above. You need exactly Java 8 to make it work.

**Comment by Consti10** [comment]
Okay I'l see.

**Comment by Consti10** [comment]
I have uninstalled then rei-installed java8 via this tutorial: http://ubuntuhandbook.org/index.php/2019/04/install-openjdk-8-ubuntu-19-04/


Then I installed sdk and ndk manually without android studio. but still the script doesn't work.
I am sure there is some small stupid mistake I have made but cannot figure out what.
Has anyone successfully used the script with ubuntu 19.X ?

![Capture](https://user-images.githubusercontent.com/16462285/73020163-5b052f80-3e25-11ea-9963-21dc0ece36e0.PNG)

**Comment by Consti10** [comment]
![Capture3](https://user-images.githubusercontent.com/16462285/73020290-9f90cb00-3e25-11ea-8b59-6ec7b8d5f19f.PNG)

**Comment by Javernaut** [comment]
According to the output, the script doesn't see the ANDROID_NDK_HOME variable.
How have you exported it and what content is inside that directory?

**Comment by Javernaut** [comment]
Probably I should add the basic check for this variable with an appropriate message, as it seems to be the common issue

**Comment by Consti10** [comment]
I have exported it using export ANDROID_NDK_HOME=$ANDROID_SDK_HOME/ndk/21.0.6113669

SDK before accordingly.

Then I run the script in the same terminal since it is not defined persistent I suppose

**Comment by Consti10** [comment]
Printenv works on both SDK and NDK, as visible from the screenshots above.

**Comment by Javernaut** [comment]
Does it work with
echo $ANDROID_NDK_HOME
?

**Comment by Javernaut** [comment]
Oh, why do you use sudo?
Try just ./ffmpeg-android-maker.sh

**Comment by Consti10** [comment]
echo $ANDROID_NDK_HOME did work, too.

But I tried it without sudo and it is running now ... thanks.

It is definitely the variable not properly set with sudo. I just tested it -
set variable via `export ANDROID_NDK_HOME=$ANDROID_SDK_HOME/ndk/21.0.6113669` without root.
Then echo variable works: `echo $ANDROID_NDK_HOME
/home/constantin/android-sdk/ndk/21.0.6113669`

sudo echo ... also works: `sudo echo $ANDROID_NDK_HOME
/home/constantin/android-sdk/ndk/21.0.6113669`

but first running sudo su - then echo .. doesn't: !
Interesting... I did not expect that. Here is a screenshot of echo with and without root:
![CaptureX](https://user-images.githubusercontent.com/16462285/73024518-ff8b6f80-3e2d-11ea-87dd-ff915cbe0397.PNG)
