### ISSUE TITLE
Docker support to fix Windows builds (and Linux/Mac)

### ISSUE THREAD

**Issue by akiller** [Javernaut/ffmpeg-android-maker#22]
Hi,

Firstly, thanks for this project - it makes building ffmpeg far easier! 

I wanted to be able to easily build this on Windows but noticed that's now not possible in v2.0.0, and last time I did try and build it on Windows using MSYS2 pre v2.0.0 I ended up with a whole range of strange build problems and just ended up installing an Ubuntu VM where it was quite straight forward.

I'd like to avoid having to use a Linux VM so I figured the best way would be to be able to build it in Docker. I've created [pull request 21](https://github.com/Javernaut/ffmpeg-android-maker/pull/21) which will build a Docker image that does all the work for you. You can mount /build/build from the Docker container to a path on your host to access to the built files.

I've updated the readme in the pull request which explains how to use it.

**Comment by Javernaut** [comment]
Hello @akiller ,

Thanks for your contribution.

Actually I wanted to reenable MSYS2 support. I just didn't have much time during last 2 months.
In a couple of days finally I'll return to my projects. And I will examine the opportunity to fix MSYS2 as well as your solution. I'm not really familiar with Docker.

**Comment by akiller** [comment]
Great. All you should need to do is [install Docker](https://docs.docker.com/install/) then run the two commands I added to the readme and wait for them to do the work for you.

Personally I would say with Docker support there's little need to support MSYS2 as this is far easier to set-up and should be more consistent as regardless of whether you're running Linux, Mac, or Windows  using the Docker method means the build process will always happen inside a containerised Ubuntu instance and you don't need to bother configuring all your paths to the NDK etc.

**Comment by Javernaut** [comment]
Hello @akiller ,

I've spent some time reviewing the Docker and the integration you made. In general I would like to thank you for the idea of abstracting the building process. However, I see a pretty narrow use case of this thing. Let me explain.

Here are pros:

1. It really allows building the FFmpeg on any machine regardless the dependencies that are necessary for it.
2. It fixes (or introduces) Windows support.

And here are cons as I see them:

1. The necessity of installing the Docker itself.
2. It doesn't run natively (even though it isn't a virtual machine).
3. On macOS the Docker does use the Linux virtual machice.
4. Inside the container the Android SDK and Android NDK will be downloaded as well as a lot of other dependencies.

The first 3 points here are pretty small. But the 4th one is major I think. In my opinion the main use case of ffmpeg-android-maker is to be executed on an Android developer machine which already has Android SDK and Android NDK installed. So I don't think downloading of them again are necessary at all. Even caching of them isn't necessary inside the container.

For now I see Docker only as a way of replacing MSYS2 on Windows and definitely not as a primary way of executing the ffmpeg-android-maker on any machine.
For that reason I would like to move the description of how to use it to a separate Wiki page and leave only a mentioning in the README.md.

On Linux and macOS I would keep executing the ffmpeg-android-maker only natively.

As for the MSYS2, I still think it is a viable way to execute the script. Soon I'll update its integration and prepare new Wiki pages with proper descriptions of how to execute the script with necessary preparations.

**Comment by Javernaut** [comment]
And one more thing @akiller ,

I actually didn't succeed in making Docker work with this particular repository. Could you please have a look:

<img width="1164" alt="Screenshot 2020-03-20 at 16 26 31" src="https://user-images.githubusercontent.com/979018/77228593-1ed61d00-6b91-11ea-90bd-e501e683e7e1.png">

The `sources` directory is created to cache the sources of FFmpeg and its external dependencies. It doesn't exist before the first execution of the script. And your Docker script tries to copy it for some reason. Please, have a look at this use case when there are no caches at all.

And another thing. Actually a question. Is it really necessary to install `platforms;android-29`? My Travis CI integration downloads a pure Android SDK and doesn't install it. And it works fine.

**Comment by akiller** [comment]
@Javernaut,

I agree - if you're running Linux and already have the NDK installed and set-up then you probably don't need this as your script already helps make the build process very simple.

However if like me you're running Windows and don't really want to set-up MSYS2 then clearly this is useful. 

* The necessity of installing the Docker itself.

Sure. The Docker approach is just an option available, you obviously don't need to use it. Installing Docker is no harder than installing MSYS2 on Windows and I'd imagine quite a lot of people already use it, certainly if you're a full-stack developer.

* It doesn't run natively (even though it isn't a virtual machine).

True, but this isn't a bad thing because it provides a consistent build platform. 

E.g., imagine there's a weird bug in the Windows NDK that doesn't exist in the Linux one or a weird bug in the NDK if you're running OSX Catalina that causes the library to crash on the phone - I'm clearly making these examples up, but hopefully my sentiment makes sense!

* On macOS the Docker does use the Linux virtual machice.

It does on Windows too, it's managed entirely by Docker.

* Inside the container the Android SDK and Android NDK will be downloaded as well as a lot of other dependencies.

This is the Docker way really. I did try and keep it as lean as I could.

It's done like this so you can guarantee consistency. So if you and I both ran the same Dockerfile on our PCs we could be sure we're using the same version of the NDK for example, and have the same build tools (e.g., clang) installed. Perhaps you have r20 installed on your PC but this project only supports r18: you can easily fulfil that dependency via Docker.

You only need to build the image once, you don't need to build it every time so it doesn't have to keep downloading all these dependencies unless of course you change the NDK/SDK versions.

* For now I see Docker only as a way of replacing MSYS2 on Windows and definitely not as a primary way of executing the ffmpeg-android-maker on any machine.
For that reason I would like to move the description of how to use it to a separate Wiki page and leave only a mentioning in the README.md.
On Linux and macOS I would keep executing the ffmpeg-android-maker only natively.

I agree. If you're already using Linux there's likely no need to use this, unless you have some weird incompatible built tool versions installed like I mentioned before.

* As for the MSYS2, I still think it is a viable way to execute the script. Soon I'll update its integration and prepare new Wiki pages with proper descriptions of how to execute the script with necessary preparations.

I wonder if it might be better to look at using [WSL2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-about) rather than MSYS2 on Windows. Like MSYS2 it just gives you a Linux terminal, but behind the scenes runs a lightweight Linux VM in Hyper-V. Your original script might actually work fine using it without any changes because of this.

**Comment by akiller** [comment]
> I actually didn't succeed in making Docker work with this particular repository. Could you please have a look:
> The sources directory is created to cache the sources of FFmpeg and its external dependencies. It doesn't exist before the first execution of the script. And your Docker script tries to copy it for some reason. Please, have a look at this use case when there are no caches at all.

Oops my mistake. I've removed this and it now builds.

> And another thing. Actually a question. Is it really necessary to install platforms;android-29? My Travis CI integration downloads a pure Android SDK and doesn't install it. And it works fine.

Oh OK, I've removed it and it seems to still build for me. I've pushed the changes 🙂.

**Comment by Javernaut** [comment]
Hello @akiller ,

I've been thinking about Docker for a while and your particular implementation. I came up with certain ideas.

From the very beginning I didn't like the idea of placing Docker files right in the root of the repository. I think tooling-specific files shouldn't live there. Even the .travis.yml bothers me :)

Also, I don't really like the idea of preparing a Docker image for building the specific version of ffmpeg-android-maker. Here I mean the specific state of the ffmpeg-android-maker repo, because you upload it to the image during the construction. So I would leave only a build-ready image and provide the whole ffmpeg-android-maker directory in `docker container run` command.

The whole point is to work on those scripts directly on a developer machine and Docker should just pick up whatever you are working on, ins't it?

By merging the aforementioned ideas I came up to the idea of **creating a separate Github repository for building Docker images and share them via Docker HUB**. Hanse the Docker HUB can build and publish images from a Github repo automatically.
Thus the ffmpeg-android-maker will be clean of Docker integration and still users will be able to build their custom images if they want by working with that separate repository.

I'm really excited with this idea, hope to implement it in reasonable time. I start liking Docker.

Really appreciate your participating and introducing Docker to me. I'll leave this issue opened till it's done, but will close your pull request.

**Comment by Javernaut** [comment]
And one more thing @akiller ,

One more thank for the idea to using WSL on Windows. The actual Linux virtual machine is bigger in size than MSYS2, but provides better environment than MSYS2 emulation.

**Comment by akiller** [comment]
@Javernaut,

> I've been thinking about Docker for a while and your particular implementation. I came up with certain ideas.
>
> From the very beginning I didn't like the idea of placing Docker files right in the root of the repository. I think tooling-specific files shouldn't live there. Even the .travis.yml bothers me :)

Haha fair enough!

> Also, I don't really like the idea of preparing a Docker image for building the specific version of ffmpeg-android-maker. Here I mean the specific state of the ffmpeg-android-maker repo, because you upload it to the image during the construction. So I would leave only a build-ready image and provide the whole ffmpeg-android-maker directory in docker container run command.
>
> The whole point is to work on those scripts directly on a developer machine and Docker should just pick up whatever you are working on, ins't it?
>
>By merging the aforementioned ideas I came up to the idea of creating a separate Github repository for building Docker images and share them via Docker HUB. Hanse the Docker HUB can build and publish images from a Github repo automatically.
>Thus the ffmpeg-android-maker will be clean of Docker integration and still users will be able to build their custom images if they want by working with that separate repository.
>
> I'm really excited with this idea, hope to implement it in reasonable time. I start liking Docker.
>
> Really appreciate your participating and introducing Docker to me. I'll leave this issue opened till it's done, but will close your pull request.

Sure, no problem. At first I also wasn't very sure about the benefits of Docker but the more I use it the more I like it. It generally just makes things very easy and rapid to deploy.

So I got a bit of free time today and I decided to build [https://github.com/akiller/ffmpeg-android-maker-docker](ffmpeg-android-maker-docker) which I think solves your problem.

Please check the readme on the project as it explains it in more detail, but effectively this either lets you build from a specific Github commit (which is what 99% of people would use), or you can mount your current working directory and build using that which is useful if you're developing ffmpeg-android-maker but want to build using Docker without having to commit the code.

It also removes all of your code from the base image which was one of the problems you raised.

Hope to hear your feedback!

**Comment by Javernaut** [comment]
Hello @akiller ,

It is really nice when someone is interested in my project and does such a contribution.

However, I think I have to reimplement the same thing myself. Here are my reasons:
- I really want to practice with Docker myself. I think this is the most important reason.
- In this case publishing to Docker HUB will be easier for me.
- You and me have just a little different considerations of what the Docker image should do (I'll explain below).
- I realised there should be done one important change in this repo which actually may impact the Docker image construction.

I'm not sure in usefulness of both environment variables (EXTRA_BUILD_CONFIGURATION_FLAGS and ANDROID_MAKER_COMMIT) you are featuring to use.

The idea of ffmpeg-android-maker is to be able to customise the build script and compile the FFmpeg the way that is suitable for a particular project. For now the whole repo serves the particular Android app - [WhatTheCodec](https://github.com/Javernaut/WhatTheCodec). For example, ffmpeg-android-maker doesn't compile any encoders and muxers.
So this means ANDROID_MAKER_COMMIT is not really usable for anyone except me. And EXTRA_BUILD_CONFIGURATION_FLAGS can potentially have flags that will clash with those that are already in ffmpeg-android-maker's script.
Moreover, particular customisation may involve creating of new shell scripts (when a new external library is integrated). And I think it decreases the value of EXTRA_BUILD_CONFIGURATION_FLAGS even more.
I strongly believe users should be able to edit all files in the ffmpeg-android-maker directly and Docker should just pickup it and build.

I don't want to delegate too much work to Docker image and would like have it only as a thing that can build whatever a developer has done in his/her ffmpeg-android-maker repo.

Just a side note, I see you didn't configure the image with necessary software to build libdav1d. Apart from necessary software I feel like the list of software that is getting installed is a little bit bigger than it should be. I need to check it out. 

The 'important change' I mentioned is that I realised the ffmpeg-android-maker should be more generic and serve **both** as a basis for customisation and as an example of such a customisation. So I'll change the master branch to compile FFmpeg without any customisation and will create a separate branch for my particular Android app to be the example.

I'm sorry for being such a bad collaborator by just discarding your work and saying that I'll do it myself, but I have reasons. But I'm really grateful for your ideas and the opportunity to learn a new technology.

**Comment by akiller** [comment]
> However, I think I have to reimplement the same thing myself. Here are my reasons:
>     * I really want to practice with Docker myself. I think this is the most important reason.
>     * In this case publishing to Docker HUB will be easier for me.
>     * You and me have just a little different considerations of what the Docker image should do (I'll explain below).

Haha don't worry about it. My repo solves the problems we have. You're obviously welcome to take whatever you want from it, and feel free to drop me a message if you need some Docker help. I'm not an expert but I've built quite a few different images.

Having this available on Dockerhub would be great.

> 
> I'm not sure in usefulness of both environment variables (EXTRA_BUILD_CONFIGURATION_FLAGS and ANDROID_MAKER_COMMIT) you are featuring to use.
> 
> The idea of ffmpeg-android-maker is to be able to customise the build script and compile the FFmpeg the way that is suitable for a particular project. For now the whole repo serves the particular Android app - [WhatTheCodec](https://github.com/Javernaut/WhatTheCodec). For example, ffmpeg-android-maker doesn't compile any encoders and muxers.
> So this means ANDROID_MAKER_COMMIT is not really usable for anyone except me. And EXTRA_BUILD_CONFIGURATION_FLAGS can potentially have flags that will clash with those that are already in ffmpeg-android-maker's script.
> Moreover, particular customisation may involve creating of new shell scripts (when a new external library is integrated). And I think it decreases the value of EXTRA_BUILD_CONFIGURATION_FLAGS even more.
> I strongly believe users should be able to edit all files in the ffmpeg-android-maker directly and Docker should just pickup it and build.

I see what you're trying to say now and why you thought my approach was strange! 

As it happens for our requirements building directly from Github was fine we didn't need to customise any of the scripts.

The only thing we needed to do was pass the --disable-gpl flag because we need to use it in a commercial app which was the sole reason I added EXTRA_BUILD_CONFIGURATION_FLAGS.

> I don't want to delegate too much work to Docker image and would like have it only as a thing that can build whatever a developer has done in his/her ffmpeg-android-maker repo.

It would perhaps be a good idea to add some default build scripts for different scenarios and let the user choose one when they create the container, e.g., let's say you create one called *swscale* in /ffmpeg-android-maker that will build libswscale, and set a gpl=0 environment variable for the script to read:

```
docker run --rm -e "gpl=0" ffmpeg-android-maker swscale.sh
```
 
And if they wanted to use their own bespoke scripts they could just mount a volume to /ffmpeg-android-maker containing the script and specify to execute that instead:

```
docker run --rm -v /path/to/my/custom/scripts:/ffmpeg-android-maker ffmpeg-android-maker mycustomscript.sh
```

I'm just thinking out loud, I'm not sure if this is the best way or not.


> Just a side note, I see you didn't configure the image with necessary software to build libdav1d. Apart from necessary software I feel like the list of software that is getting installed is a little bit bigger than it should be. I need to check it out.

Oh OK. We're only using libavutil and libswscale so that we can resize images using Lanczos in Android.

One thing you (or any user) could do with Docker is create your base image that contains the minimal build tools and then you could create another Dockerfile that builds on top of it and generates a new image for special cases like libdav1d,  e.g.:

```
FROM ffmpeg-android-maker:latest

RUN apt-get update && \
	apt-get install -y --no-install-recommends \
	...
```


> I'm sorry for being such a bad collaborator by just discarding your work and saying that I'll do it myself, but I have reasons. But I'm really grateful for your ideas and the opportunity to learn a new technology.

Don't worry about it, I don't like people touching my code either 😊

The fact you're exploring Docker and how to improve the project going forwards is really the best option.

**Comment by Javernaut** [comment]
Hey @akiller ,

I've finished my own implementation. There is even a Docker image available on Docker Hub. It was really nice experience.

There is even a separate [release](https://github.com/Javernaut/ffmpeg-android-maker/releases/tag/v2.1.1) for it. I mentioned you there :)

Stay healthy and have a good day!

**Comment by akiller** [comment]
That's great! Thanks for letting me know and glad you got it all working in the end.
