### ISSUE TITLE
Undefined reference to 'main'

### ISSUE THREAD

**Issue by st4ycool** [Javernaut/ffmpeg-android-maker#23]
Hello. Thank you for the awesome script, It was such a pleasure after all to just see how ffmpeg is simply being compiled)

I have a question that is **not** related to this repository, but I will be very happy if you could take a look at it:

I am trying to build static libs of ffmpeg 4.0.2 ver to use it with JNI in my Android Studio project.
Configuration:

```
ffmpeg:
    $(TBZUNPACK) $(FFMPEG)
    # include/binder,cutils,utils,multimedia/stagefright
    cd $(FFMPEGDIR); cat ../patches/android-ffmpeg-*.diff | patch -p1
    #tar -C $(DEPENDENCIES)/ -xjf $(STAGEFRIGHT).tbz
  
    cd $(FFMPEGDIR); ./configure 
        --prefix=$(DEPENDENCIES) \
        --enable-pic \
        --enable-libmp3lame \
        --enable-libtheora --enable-libvorbis \
        --enable-libx264 --enable-libvpx \
        --enable-libopus \
        --enable-gpl --enable-nonfree --disable-outdev=sdl \
        --disable-doc \
        --enable-cross-compile 
        --enable-shared --cross-prefix=$(CCPREFIX) \
        --target-os=linux $(FFMPEG_ANDROID) \
        --extra-cflags="$(ANDROID_CFLAGS) -I$(DEPENDENCIES)/include   $(ANDROID_EXTRA_HEADERS)" \
        --extra-cxxflags="$(ANDROID_CFLAGS) -I$(DEPENDENCIES)/include $(ANDROID_EXTRA_HEADERS)"\
        --extra-ldflags="$(ANDROID_LDFLAGS) -L$(DEPENDENCIES)/lib -Wl,--allow-shlib-undefined -Wl,-rpath-link=$(DEPENDENCIES)/lib"
    make -C $(FFMPEGDIR) $(PARALLEL_MAKE)
    make -C $(FFMPEGDIR) install
    rm -rf $(FFMPEGDIR)
```

and I am getting my build failed with this error:

```
 /home/android-ndk/./platforms/android-16/arch-arm/usr/lib/crtbegin_dynamic.o:crtbrand.c:function _start: error: undefined reference to 'main'
collect2: error: ld returned 1 exit status
Makefile:107: recipe for target 'ffplay_g' failed
make[1]: *** [ffplay_g] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/ffmpeg-4.0.2'
Makefile.android:180: recipe for target 'ffmpeg' failed
make: *** [ffmpeg] Error 2
```

I can't understand what function main is doing there, because I thought I am compiling libraries, not executables. 

Also, I tried to implement this configuration into your script. Script worked out ok, but no files were generated =(

**Comment by Javernaut** [comment]
Hello @st4ycool .

As I see you don't pass certain flags to the `configure` script of FFmpeg that would disable `ffmpeg` and `ffprobe` executables from being compiled. You can do that by adding `--disable-programs` flag.

You may want to add additional flags. You can find all available flags directly in the `configure` script of your version of FFmpeg [here](https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/0a155c57bd8eb92ccaf7f5857dc6ab276d235846:/configure). Or just open your `configure` script with a text editor.

I would personally recommend to use newer version of FFmpeg.

For example [here](https://github.com/Javernaut/ffmpeg-android-maker/commit/734a4e98c41576b8b9fcf032e0754315b5b77a82) is my flags that I add to disable (don't compile) certain parts of FFmpeg.

**Comment by Javernaut** [comment]
@st4ycool ,

One more thing.

I've noticed you wrote that you want to build **static** libraries, but you pass `--enable-shared` flag to `configure` script.

**Comment by s7aycool** [comment]
@Javernaut, thank you for the answer and recommendations.

1. I will try --disable-programs and give feedback here.
2. I have a source code of moded ffmpeg 4.0.2, so I can't use newer versions right now. 
Also, how much better perfomance newer versions can bring to video decoding?
3. **--enable-shared** I added this flag as a workaround to patch error that I mentioned in this issue. But I am really newbie to compiling sources and now I see my mistake ) 
Thank you!

**Comment by Javernaut** [comment]
@s7aycool 

I'm afraid I don't have any performance comparison of different versions of FFmpeg. 
I just know that FFmpeg 4.1 and above is perfectly compilable for Android without any source code modifications.

**Comment by st4ycool** [comment]
@Javernaut --disable-programs worked out like charm ) thank you so much!
