### ISSUE TITLE
Couldn't compile ffmpeg for android using ubuntu

### ISSUE THREAD

**Issue by IamBinishMathew** [Javernaut/ffmpeg-android-maker#28]
binishmathew@VirtualUbuntu:/ffmpeg-android-maker-master$ sudo ./ffmpeg-android-maker.sh
[sudo] password for binishmathew: 
Getting source code of the component: ffmpeg
Using FFmpeg source archive: 4.2.3
Ensuring sources of ffmpeg in ffmpeg-4.2.3
/home/binishmathew/ffmpeg-android-maker-master/scripts/common-functions.sh: line 20: curl: command not found
tar: ffmpeg-4.2.3.tar.bz2: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
rm: cannot remove 'ffmpeg-4.2.3.tar.bz2': No such file or directory
Building the component: ffmpeg
./ffmpeg-android-maker.sh: line 112: cd: /home/binishmathew/ffmpeg-android-maker-master/sources/ffmpeg/ffmpeg-4.2.3: No such file or directory
/home/binishmathew/ffmpeg-android-maker-master/scripts/ffmpeg/build.sh: line 25: ./configure: No such file or directory
binishmathew@VirtualUbuntu:~/ffmpeg-android-maker-master$

**Comment by Javernaut** [comment]
Hello @IamBinishMathew ,

According to the logs you have provided your machine lacks `curl` tool. Just install it with `sudo apt-get install curl` command and rerun the script again.

**Comment by IamBinishMathew** [comment]
Thanks for the reply, but it didn't work well.

binishmathew@VirtualUbuntu:~/ffmpeg-android-maker-master$ sudo ./ffmpeg-android-maker.sh
[sudo] password for binishmathew: 
Getting source code of the component: ffmpeg
Using FFmpeg source archive: 4.2.3
Ensuring sources of ffmpeg in ffmpeg-4.2.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.4M  100 10.4M    0     0  87181      0  0:02:05  0:02:05 --:--:--   99k
Building the component: ffmpeg
$HOME/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android16-clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
binishmathew@VirtualUbuntu:~/ffmpeg-android-maker-master$

**Comment by Javernaut** [comment]
@IamBinishMathew , actually my advice helped. The source code for FFmpeg is downloaded according to the new logs.
However, I see you have another problem. Seems like you incorrectly set up the `ANDROID_NDK_HOME` variable. It contains '$HOME' as text. Perhaps you escaped the first '$' char accidentally. What does the `echo $ANDROID_NDK_HOME` command says?

**Comment by IamBinishMathew** [comment]
Yes. I had to set environment variables again. This time I was able to compile ffmpeg. Thanks

**Comment by Javernaut** [comment]
You're welcome.
