### ISSUE TITLE
how to enable codec for libfdk-aac

### ISSUE THREAD

**Issue by aDropOfWater** [Javernaut/ffmpeg-android-maker#30]
![QQ截图20200608102210](https://user-images.githubusercontent.com/11939185/83987205-101e2b80-a972-11ea-80d5-70fca8a141ad.png)
this is my sc,but when compile fdkaac has error,
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Javernaut** [comment]
Hello @aDropOfWater ,

Currently I don't have a capacity to dive deep into this problem. 
The error message you provided is too generic and I don't have even an advice for it.

I'll try to help with that in nearest weeks.

**Comment by Javernaut** [comment]
Hi @aDropOfWater ,

I've briefly checked this library integration to FFmpeg and here are some news.
This library isn't free. The FFmpeg configure script allows its integration only with `--enable-nonfree` flag. Here is the original description of this flag:
```
  --enable-nonfree         allow use of nonfree code, the resulting libs
                           and binaries will be unredistributable [no]
```
I do have plans to support nonfree and gpl libraries gracefully at some point in the future, but not in the nearest.
