### ISSUE TITLE
Android ffmpeg binary and other .so files execution error

### ISSUE THREAD

**Issue by mihir0109** [Javernaut/ffmpeg-android-maker#31]
Firstly, Thanks for simplifying all the steps in single script..
Have executed script and got ffmpeg/ffprobe binary and other .so files i.e. libavcodec.so, libavdevice.so, libavfilter.so, libavformat.so, libavutil.so, libswresample.so, libswscale.so.

Now when applying to android project using below process:
I have put all these .so files in jniLibs->arm64-v8a->... and same for other 3 CPU architecture like x86 and x86_64.

I have put binary ffmpeg and ffprobe in assets folder with similar CPU architecture. i don't have JNI folder, not any C++ native code in my project.

Now i am loading these so files using System.loadLibrary("") for all 7 .so files and it loads successfully.

Have moved ffmpeg  binary from assets to data/data/ folder.
But when I run any command: it shows error:
CANNOT LINK EXECUTABLE "/data/user/0/<pkg_name>/files/ffmpeg": library "libavdevice.so" not found

What could be the reason? any idea what mistakes I am doing?

I went thru your part 2 of integration (https://github.com/Javernaut/WhatTheCodec), but that's using JNI and Cpp, which is out of scope for me as not aware about JNI and C coding and calling native methods from java code.

**Comment by Javernaut** [comment]
Hello @mihir0109 ,

In the past I succeeded in executing ffmpeg binary in Android's terminal only (both via adb and from Android device itself). I haven't embedded it to an Android application.

The ffmpeg binary searches for *.so files by a relative path. All these *.so files should be accessible by `../lib/*.so` relatively to ffmpeg binary. The ffmpeg binary doesn't expect the installation directory to be changed anyhow.

You can try placing all necessary files in assets rather than in jniLibs and move them all to device's storage. And then the binary should work properly.

**Comment by Javernaut** [comment]
@mihir0109 ,

Consider the 'portable' application. It has its file structure which shouldn't be messed. Only this way such an app can work if you just copy it into a target environment.

That is why you shouldn't change the structure of what FFmpeg building process prepared for you.

**Comment by mihir0109** [comment]
Hi @Javernaut ,

Thanks a lot for quick reply and suggestion.
Tried moving all .so files to data/ folder same like ffmpeg, but still getting same error. 
CANNOT LINK EXECUTABLE "/data/user/0/com.app.picodio/files/ffmpeg": library "libavdevice.so" not found

**Comment by Javernaut** [comment]
@mihir0109 ,

Did you make the structure of files on the device like at the image below?

<img width="187" alt="image" src="https://user-images.githubusercontent.com/979018/89001945-6ff6da00-d304-11ea-9b39-c4e7fea8240a.png">

This way it should work properly.

**Comment by mihir0109** [comment]
I have put all these .so files in jniLibs->arm64-v8a->... and same for other 3 CPU architecture like x86 and x86_64.
And all files in assets -> arm64-v8a -> ... (all 7 .so files and ffmpeg and ffprobe binary)

then moving all these assets file to data/ folder. 




 static boolean copyBinaryFromAssetsToData(Context context, String fileNameFromAssets, String outputFileName) {
		
		// create files directory under /data/data/package name
		File filesDirectory = getFilesDirectory(context);
		
		InputStream is;
		try {
			is = context.getAssets().open(fileNameFromAssets);
			// copy ffmpeg file from assets to files dir
			final FileOutputStream os = new FileOutputStream(new File(filesDirectory, outputFileName));
			byte[] buffer = new byte[DEFAULT_BUFFER_SIZE];
			
			int n;
			while(EOF != (n = is.read(buffer))) {
				os.write(buffer, 0, n);
			}

            Util.close(os);
            Util.close(is);
			
			return true;
		} catch (IOException e) {
			Log.e("issue in coping binary from assets to data. ", e);
		}
        return false;
	}
my cpu architecture is: arm64-v8a
copyBinaryFromAssetsToData(context,  cpuArchNameFromAssets + File.separator + "libavcodec.so", "libavcodec.so");

**Comment by Javernaut** [comment]
`System.loadLibrary(xxx);` isn't needed at all if you don't use the JNI bindings.

I would like to repeat again the thing regarding file structure of binaries and shared libraries. They have to be in separate directories with specific names. See my screenshot above. You shouldn't place into a single directory - that just will not work.

**Comment by mihir0109** [comment]
Hello,

Yes, but i said above, try moving .so files from assets folder to data/ folder same like ffmpeg binary. 
The ffmpeg binary searches for *.so files by a relative path. All these *.so files should be accessible by ../lib/*.so

i tried earlier removing system.loadlibrary, but same issue.

**Comment by mihir0109** [comment]
Is there any way i can create ffmpeg itself with all necessary .so files.. i.e. using this scripe, i can generate ffmpeg with just 250 kb of binary.. can i get it which includes all .so files i.e. ffmpeg binary itself 20 mb, so other .so files dont required?

**Comment by Javernaut** [comment]
Not sure if this is possible. The ffmpeg binary is just a facade for a set of av** libraries. And there are other binaries that work with these shared libraries as well.

**Comment by Javernaut** [comment]
I've compiled the ffmpeg binary and tried everything myself. Indeed there is an issue just as you described: "CANNOT LINK EXECUTABLE "./ffmpeg": library "libavdevice.so" not found".

I'm sure the executable worked for me in the past, but I don't remember details.

I'll investigate this issue further, but it isn't my priority for now.

**Comment by mihir0109** [comment]
Thanks a lot champ.. waiting for the updated one if can be fixed soon.

**Comment by Javernaut** [comment]
Transferred this issue to private Jira
