### ISSUE TITLE
libavcodec.so: error: undefined reference to 'log2'

### ISSUE THREAD

**Issue by SagittariusSum** [Javernaut/ffmpeg-android-maker#32]
libavcodec/libavcodec.so: error: undefined reference to 'log2'
libavcodec/libavcodec.so: error: undefined reference to 'log2'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ffprobe_g] Error 1
make: *** Waiting for unfinished jobs....
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ffmpeg_g] Error 1

How to solve this problem?
NDK:21.3
What's the reason I haven't found the problem for a long time..

**Comment by SagittariusSum** [comment]
INSTALL	doc/libswresample.3
INSTALL	doc/libavcodec.3
INSTALL	doc/libavformat.3
INSTALL	doc/libavdevice.3
INSTALL	doc/libavfilter.3
LD	ffmpeg_g
libavcodec/libavcodec.so: error: undefined reference to 'log2'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ffmpeg_g] Error 1

**Comment by Javernaut** [comment]
Hi @SagittariusSum ,

I assume you are adding a new external library support.

The `log2()` is a function from `libm` library. Some external libraries require a `-lm' linker flag to be added to the `--extra-ldflags` argument of the FFmpeg's configure script.

I already added a support of adding such a flag in case it is actually needed. Have a look here:
https://github.com/Javernaut/ffmpeg-android-maker/blob/master/scripts/libtwolame/build.sh#L17

**Comment by SagittariusSum** [comment]
@Javernaut 
谢谢，我没有加新的第三方插件，不过我先试试加上 "-lm" 试试。

**Comment by SagittariusSum** [comment]
@Javernaut 
      hi。I didn't add a new third-party plug-in, but I'll try to add "- LM" first.Thank you.

**Comment by SagittariusSum** [comment]
@Javernaut

**Comment by SagittariusSum** [comment]
![1596125059440](https://user-images.githubusercontent.com/29267588/88946104-6b5d0200-d2c1-11ea-8f73-af3aec95c932.jpg)

**Comment by SagittariusSum** [comment]
Is it related to my computer system?     My computer is MacOS Catalina.

**Comment by Javernaut** [comment]
@SagittariusSum , are you using the ffmpeg-android-maker or just trying to create your own script for compilation?

If you are using my script, then please specify the command how you got the 'log2' error.

As for the naming for libavcodec.so.XX - you have to add `--target-os=android` argument to FFMpeg's configure script and that should do the trick removing those digits.

**Comment by SagittariusSum** [comment]
我在使用你的ffmpeg-android-maker

**Comment by Javernaut** [comment]
@SagittariusSum , let's stick to English language.

Can you provide me the command that caused the 'log2' error?

And again about the libavcodec.so.XX. I've just checked on macOS Catalina. The terminal prints the name with digits in the end, but actual SO files are installed to the `build` properly (i.e. without these digits).

Do you need more help on this?

**Comment by SagittariusSum** [comment]
The other third-party libraries are OK, but the libaom reference reports an error.

**Comment by SagittariusSum** [comment]
./ffmpeg-android-maker.sh -all

**Comment by Javernaut** [comment]
This command assembles literally everything that is supported right now. Specifically it assembles the encoder of libaom. The thing is the encoder requires at least Android API 18 to be compiled. So the proper command to assemble everything would be `./ffmpeg-android-maker.sh -all -android=18`

**Comment by Javernaut** [comment]
I think the `-all` flag is rarely needed, I think. It was made for testing purposes mostly.
The idea of ffmpeg-android-maker is to configure the build scripts to produce the smallest binaries that yet solve your problem.

**Comment by SagittariusSum** [comment]
Thank you very much for your patience. For someone like me who has just learned ffmpeg, your script is very good.

I use - all because the app I want to make is a video editing product.

I'll add a lot of third-party libraries later.
Thanks again
