### ISSUE TITLE
Enable static builds

### ISSUE THREAD

**Issue by drunkenjabberwocky** [Javernaut/ffmpeg-android-maker#33]
Hello, thank you for providing these convenient scripts. 

I would like to know if you would be willing to consider adding an option to specify whether the binaries are built as static or as shared. I am able to build static binaries if I disable the shared flag and enable the static flag in the script scripts/ffmpeg/build.sh and do not provide any arguments to the script. But if I provide the --enable-all-free argument to the script then the build fails with a number of errors.

**Comment by Javernaut** [comment]
Hello again,

This actually sounds as a good idea. Thank you.

I will definitely look into it, but can't say it will be implemented soon, as I'm totally out of capacity for now.

**Comment by drunkenjabberwocky** [comment]
The errors that I experienced were actually due to a number of modifications that I made to the scripts. The binaries are generated successfully and only require a small modification is required when building with the --enable-all-free argument (https://github.com/Javernaut/ffmpeg-android-maker/blob/master/scripts/libtwolame/build.sh#L17).
Thanks
