### ISSUE TITLE
Licence free build

### ISSUE THREAD

**Issue by drunkenjabberwocky** [Javernaut/ffmpeg-android-maker#34]
Using the --enable-all-free argument produces builds that do not include GPL2 code, but the resulting builds still include encoders/decoders and muxers/demuxers that require licences (ex. aac). Would you consider adding an option to generate builds that do not include components that require licences (ex. --exclude-licenced-encoders, --exclude-licenced-decoders, --exclude-licenced-muxers, --exclude-licenced-demuxers).
Thanks

**Comment by Javernaut** [comment]
Hello @drunkenjabberwocky ,

I wouldn't like enabling/disabling certain components of FFmpeg via ffmpeg-andorid-maker's arguments. Such customization should be done explicitly by changing respective shell scripts.

This project is intended to be a starting point for compiling the FFmpeg and external libraries according to someone's specific needs. I prefer this project to be generic enough to suit needs of everyone. The flags that you described look rather narrow scoped.

Flags like `--enable-all-free` and `--enable-all-gpl` were made for testing purposes mostly.

**Comment by drunkenjabberwocky** [comment]
Okay, that's reasonable. I'll continue to enable or disable components as needed by editing the scripts. Thanks
