### ISSUE TITLE
There is no x264.so after ffmpeg x264 cross compilation

### ISSUE THREAD

**Issue by SagittariusSum** [Javernaut/ffmpeg-android-maker#36]
./ffmpeg-android-maker.sh -all-gpl

No error is reported, but the so file of x264 cannot be found

**Comment by Javernaut** [comment]
There shouldn't be any x264.so, because all external libraries are built as static libs (you can find them in `build`directory). They are embedded into FFmpeg's shared libraries.

**Comment by SagittariusSum** [comment]
Thank you very much

**Comment by Javernaut** [comment]
You're welcome
