### ISSUE TITLE
Can't open libavfilter/libavfilter.version

### ISSUE THREAD

**Issue by vevev** [Javernaut/ffmpeg-android-maker#39]
./ffbuild/pkgconfig_generate.sh: 21: .: Can't open libavfilter/libavfilter.version
make: *** [ffbuild/library.mak:102: libavdevice/libavdevice.pc] Error 127

My OS: ubuntu 20

**Comment by Javernaut** [comment]
Your message isn't informative at all.

What script did you use? I assume you made some changes to my scripts as I never faced that issue before.

What command did you use to execute the script?

**Comment by Javernaut** [comment]
@vevev , will you provide some information on that?
