### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by v4ekmarev** [Javernaut/ffmpeg-android-maker#40]
Hello, I've tried to build the .so files using Android Studio and terminal, but i get some errors.
I set in check-host-machine.sh

export ANDROID_SDK_HOME=$HOME/Android/sdk
export ANDROID_NDK_HOME=$ANDROID_SDK_HOME/ndk/21.3.6528147

FFmpeg downloads, but after getting 
from terminal = 
```
Getting source code of the component: ffmpeg
Using FFmpeg source archive: 4.3.1
Ensuring sources of ffmpeg in ffmpeg-4.3.1
Building the component: ffmpeg
/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android16-clang is unable to create an executable file.
C compiler test failed.
```

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

from android studio = 
`ffmpeg-android-maker/ffmpeg-android-maker.sh:92: bad substitution`

Can you help?

**Comment by Javernaut** [comment]
Hello @v4ekmarev ,

According to the logs you showed the compiler path isn't properly setup. This is because the script which evaluates this path doesn't see the ANDROID_NDK_HOME variable.

I would rather do your changes in the ffmpeg-android-maker.sh script itself. In this case these variables with be definitely available in all scripts.

Or you can execute these `export` commands in the terminal itself before executing the ffmpeg-android-maker.sh.

Or you can leave your changes where they are and add the `source` command to the beginning [this line](https://github.com/Javernaut/ffmpeg-android-maker/blob/master/ffmpeg-android-maker.sh#L22):

`source ${SCRIPTS_DIR}/check-host-machine.sh || exit 1`

In all cases these variables should be picked up properly.

**Comment by v4ekmarev** [comment]
Thanks for this quick reply.I tried all the ways that you wrote, but error in terminal and studio the same.

ndk path= 
<img width="237" alt="Screenshot 2020-10-21 at 19 38 04" src="https://user-images.githubusercontent.com/7426491/96720779-677ae080-13d5-11eb-82a3-1a3208cea320.png">

export ANDROID_SDK_HOME=$/Users/vladlen/Library/Android/sdk
export ANDROID_NDK_HOME=$/Users/vladlen/Library/Android/sdk/ndk/21.3.6528147
inside ffmpeg-android-maker.sh

<img width="708" alt="Screenshot 2020-10-21 at 19 39 57" src="https://user-images.githubusercontent.com/7426491/96720844-7feafb00-13d5-11eb-888f-2c6f6c614c30.png">

echo $ANDROID_NDK_HOME 
/Users/vladlen/Library/Android/sdk/ndk/21.3.6528147
echo $ANDROID_SDK_HOME
/Users/vladlen/Library/Android/sdk

**Comment by Javernaut** [comment]
Hm, that is strange.

Why do you use the dollar sign at the beginning of the values of these variables? Have you tried to export them without the dollar sign?

**Comment by Javernaut** [comment]
Just a guess, but have you typed the names of these variables with any latin keyboard layout?

**Comment by v4ekmarev** [comment]
I tried without dollar sign, nothing changed.
I just checked for Latin, not found

**Comment by Javernaut** [comment]
Can you make a fork of this repo and upload your code there? I can have a proper look at it.

**Comment by Javernaut** [comment]
What I see now is that for some reason the export-build-variables.sh script doesn't see the ANDROID_NDK_HOME variable [here](https://github.com/Javernaut/ffmpeg-android-maker/blob/master/scripts/export-build-variables.sh#L16).

In my case I export these variables globally when any terminal starts (in ~/.zshrc file in case of zsh).

By the way, what shell do you use?

**Comment by v4ekmarev** [comment]
After clean and rebuild it worked. Thank you for help. Can i build ffplay?

**Comment by Javernaut** [comment]
You are welcome.

The ffplay is a command line application and can be compiled by adding `--enable-ffplay` flag to ffmpeg's configure script. The integration of this app into an android app differs from the integration of a shared library. I don't have any proper example for it right now.

**Comment by v4ekmarev** [comment]
Can you specify a line where to add it?

**Comment by Javernaut** [comment]
The configure script of the FFmpeg library is executed [here](https://github.com/Javernaut/ffmpeg-android-maker/blob/master/scripts/ffmpeg/build.sh#L28).

**Comment by v4ekmarev** [comment]
Thanks a lot. Tomorrow I will check the .so files and close the task.

**Comment by v4ekmarev** [comment]
I need more time to check everything, but I will close the task. Thanks again=)
