### ISSUE TITLE
How to open https url?

### ISSUE THREAD

**Issue by basaktamal** [Javernaut/ffmpeg-android-maker#41]
can't open https url

**Comment by Javernaut** [comment]
It would be more helpful if you provided a proper description of what actual build script you use and what command you execute.

You can also check the [configure](https://git.ffmpeg.org/gitweb/ffmpeg.git/blob_plain/3da35b7cc7e2f80ca4af89e55fef9a7bcb19c128:/configure) script for details. Look for "needed for https support". Certain required modules aren't enabled by default.

**Comment by basaktamal** [comment]
I want to open "https://prclive1.listenon.in/" url and get PCM data.

**Comment by basaktamal** [comment]
I tried to build openssl with FFMPEG. But I can not

I tried gnutls also. But failed..
Can you help me to build any of them (openssl or gnutls) with FFMPEG?

**Comment by Javernaut** [comment]
@basaktamal , sorry, I'm currently completely out of capacity.

**Comment by bugparty** [comment]
you need to add ssl library to enable ffmpeg to open https url, I am working on it.

**Comment by bugparty** [comment]
Now you could try the development branch, enable mbedtls, then it should be ok.

**Comment by Javernaut** [comment]
As of [v2.8](https://github.com/Javernaut/ffmpeg-android-maker/releases/tag/v2.8) the https urls should be supported.
