### ISSUE TITLE
script execution failed

### ISSUE THREAD

**Issue by smoil-ali** [Javernaut/ffmpeg-android-maker#43]
![Screenshot from 2020-12-25 17-44-31](https://user-images.githubusercontent.com/40652937/103135317-4090a180-46d9-11eb-9818-bfe8953996c6.png)

**Comment by Javernaut** [comment]
Hello @smoil-ali ,

Can you upload the ffbuild/config.log file from the ffmpeg directory? It should have the actual error message.
Also, please tell me what version of Android NDK you use.

**Comment by smoil-ali** [comment]
Thanks for replying @Javernaut  ,
 
I am new to this,i dont know where to find ffmpeg directory,can you tell where it is,and ndk version is 22. something.

**Comment by Javernaut** [comment]
First of all, can you switch to ndk below r22? I didn't test it yet, and seems like it has certain features that require ffmpeg-android-maker improvement.

**Comment by smoil-ali** [comment]
@Javernaut ,android studio does not provide specific version to install.i checked

**Comment by Javernaut** [comment]
You can still download the r21d (LTS) from [here](https://developer.android.com/ndk/downloads).

**Comment by Javernaut** [comment]
Android Studio allows you to install a specific version of Android NDK, by the way:
![image](https://user-images.githubusercontent.com/979018/103139533-dfbb9600-46e5-11eb-8655-572e5fe4d38e.png)

**Comment by smoil-ali** [comment]
![file1](https://user-images.githubusercontent.com/40652937/103140605-6b471e00-470a-11eb-8407-bb6e4343f6e6.png)
I tried lower version but same issue.here is snapshot

**Comment by Javernaut** [comment]
The script still uses the previous path to the NDK: /home/ali/Android/Sdk/ndk. It doesn't look like you have updated the ANDROID_NDK_HOME to point to r21d.

**Comment by smoil-ali** [comment]
![file2](https://user-images.githubusercontent.com/40652937/103147176-80589700-4774-11eb-831a-82bf473acf9f.png)
That is the path i set.

**Comment by Javernaut** [comment]
Well, according to your screenshot this path isn't used. Try to execute `export ANDROID_NDK_HOME=/home/ali/Android/Sdk/ndk/19.2.5345600` command before the ffmpeg-android-maker.sh execution.

**Comment by smoil-ali** [comment]
![file3](https://user-images.githubusercontent.com/40652937/103148241-78eabb00-477f-11eb-9975-5d7139b0af22.png)
@Javernaut , you are life savor thanks .
