### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by smoil-ali** [Javernaut/ffmpeg-android-maker#44]
![Screenshot from 2021-01-01 00-31-43](https://user-images.githubusercontent.com/40652937/103423514-d2f8df80-4bc8-11eb-952e-87022de2de22.png)
I dont know why i am getting this error?

**Comment by Javernaut** [comment]
Have you modified the scripts/ffmpeg/build.sh file somehow?

The script doesn't call 'clean' command. It calls `make clean`. And the path to `make` command comes from MAKE_EXECUTABLE variable that is set [here](https://github.com/Javernaut/ffmpeg-android-maker/blob/master/scripts/export-host-variables.sh#L31).

Have you removed `make` from your machine for some reason?

**Comment by smoil-ali** [comment]
believe me i even didn't open your file /
![build](https://user-images.githubusercontent.com/40652937/103424330-57e5f800-4bcd-11eb-8b33-1b65af6f6bda.png)

**Comment by smoil-ali** [comment]
![build2](https://user-images.githubusercontent.com/40652937/103424358-7f3cc500-4bcd-11eb-867c-13da36338de8.png)
thats the file

**Comment by Javernaut** [comment]
The script looks for the make with following command: `which make`. Perhaps it doesn't find it for some reason.
Previously you machine could execute this script successfully, so it could find the `make`. Seems like you have changed something in your environment. Try investigate it.

**Comment by smoil-ali** [comment]
my make command was not installed
