### ISSUE TITLE
Maintaining prebuilt libraries with maven central?

### ISSUE THREAD

**Issue by ScottPierce** [Javernaut/ffmpeg-android-maker#48]
I stumbled across this because I have a need for libswscale in an Android app. Have you thought about maintaining pre-built libraries for this in maven central? You seem to have done most of the work done already, and that would simplify the approach so that other people could more easily benefit from this.

Thanks for the blog posts and tutorials. It's helpful :)

**Comment by Javernaut** [comment]
Hello @ScottPierce ,

I though multiple times about the idea of publishing some kind of binaries in a distribution center. But the main focus of this whole repo is the configurability of the building process. You can strip unnecessary components of the FFmpeg and achieve the smalest possible FFmpeg binary that would serve your needs. I even presume you don't need all features that are available in swscale library and you can strip such features with just tuned ffmpeg-android-maker build scripts.

That ffmpeg-android-maker doesn't know the use cases that are expected by an arbitrary application. Moreoever, there are no general purpose bindings to native code done in this repo.
Publishing the full-featured FFmpeg binaries (with bindings) will result in relatively heavy binaries that users will have to use which directly contradicts the main goal of ffmpeg-android-maker (the smalles possible binaries).

If you are not trying to acieve the application size efficiency, than I would suggest you to check [this repo](https://github.com/tanersener/ffmpeg-kit), as it may be a better solution for you.

**Comment by ScottPierce** [comment]
Does it all have to be built into a single artifact? I'm very naive when it comes to the C/native build process, but I'd imagine each of the different features could be prepared independently, or a script could be made to generate artifacts with exactly the dependencies a person wanted. How many possible configurations of features are there?

**Comment by Javernaut** [comment]
@ScottPierce ,

Each FFmpeg library has its set of features. Swscale is one of these libraries. They are built by FFmpeg's own scripts and result in several .so files (in case of shared libraries).

You can alter the building process of each of these libraries by passing special arguments to FFmpeg's [configure](https://git.ffmpeg.org/gitweb/ffmpeg.git/blob_plain/11b489d592553da3d5e61a83482ee188005b0da9:/configure) script. Check the list of available flags inside the file. They are pretty much in the top of the file. You will find there a tone of different options.

**Comment by ScottPierce** [comment]
I see - what I mentioned was quite absurd :)
