### ISSUE TITLE
Are --disable-avfilter and disable-avdevice necessary? 

### ISSUE THREAD

**Issue by lucaszanella** [Javernaut/ffmpeg-android-maker#5]
I took these off and got compiler errors, is it why you disabled?. Than I putted back and took --disable-static off, and it still tries to build `avdevice` and `avfilter`, is that why you disabled static?

Why can't those be built? Also, is `swresample` not suitable for android too?

**Comment by Javernaut** [comment]
Hello @lucaszanella ,

The thing it that script is tuned to suit one exact purpose - to read metadata of a video file and display several frames from it. So I disabled all redundant modules to have native libraries as small as possible.

Previously I managed to compile all modules with similar script.

As for `avdevice`: it does have a compilation error I know. It is [fixed](https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/73251678c83cbe24d08264da693411b166239bc7) in current ffmpeg master branch, but it is not cherry-picked to 4.1 branch. This fix does exist in 4.2 release branch, but there is no archive for it right now. 

I consider extending the script with selecting a particular git branch or tag in the nearest future. Meanwhile you can use either release/4.2 branch of even master from ffmpeg git repository on your own.

**Comment by Javernaut** [comment]
@lucaszanella , I've just updated the script so you can set a particular FFmpeg version or a git branch. Try `release/4.2` branch. At least it should have less problems.
All details can be found [here](https://github.com/Javernaut/ffmpeg-android-maker/wiki/Setting-the-FFmpeg-version).
Enjoy :)

**Comment by Javernaut** [comment]
@lucaszanella , here is some news for you.

First I have already checked the `release/4.2` branch with avfilter, avdevice and swresample enabled. It is successfully compilable. You can find details [here](https://travis-ci.org/Javernaut/ffmpeg-android-maker/jobs/567221164).

Second. I enabled the CI integration and you can use it too for your purposes. Check the [wiki page](https://github.com/Javernaut/ffmpeg-android-maker/wiki/Build-automation) for details.
