### ISSUE TITLE
Problems with ffmpeg build on docker

### ISSUE THREAD

**Issue by A2va** [Javernaut/ffmpeg-android-maker#52]
I run ```docker run --rm ^
  -v C:\path\to\ffmpeg-android-maker:/mnt/ffmpeg-android-maker ^
  javernaut/ffmpeg-android-maker```

But Docker return this:```/usr/bin/env: 'bash\r': No such file or directory```

I saw the CRLF line ending cause problems on Windows and I tried to use LF but it will return the same error.

**Comment by A2va** [comment]
I tried to rebuild a new docker image and I execute the build script and the error is still the same. 
I create a simple bash script with a echo. That's work.
And when I added `#!/usr/bin/env bash` to my script the same error appear
It's possible to add space between `#` and `!/usr/bin/env bash` because with that it worked ?

**Comment by Javernaut** [comment]
Hello @A2va ,

I've just got a free minute for a brief investigation regarding this issue. I've setup my Windows machine: installed the Docker, pulled the image and executed the command by my own manual. And it actually worked without any problem. So I don't think there is an issue on the side of ffmpeg-android-maker.

The downloaded the source code of ffmpeg-android-maker from Github as a zip archive. And I have a guess that you just cloned the repository. And my another guess is that your [global autocrlf setting](https://github.com/pyenv/pyenv/issues/1725#issuecomment-724689291) cripples the code you pull. Can you check it out?
Also, please try zip archive downloading and tell me if it works for you without any changes to code and the docker image.

**Comment by A2va** [comment]
Yes I cloned the repo and my autocrlf was set to true. Docker works with the downloaded zip of the repo. So this issue is resolve. Thanks !

**Comment by Javernaut** [comment]
You are welcome!
