### ISSUE TITLE
Need Minimal Configuration for sequence of images to MP4.

### ISSUE THREAD

**Issue by sabishm** [Javernaut/ffmpeg-android-maker#61]
Hi,

I need minimal configuration for convert the sequence of images to mp4. Please give.

No need audio and any other formats. Just bitmaps to mp4 video.

Thank you.

**Comment by Javernaut** [comment]
Hello @sabishm ,

This project automates downloading and building of the FFmpeg library per se. Fulfilling the particular requirements of your project is actually your responsibility, as you know your project better and it is you how will integrate the SO libraries and support it in future.

The only thing I can direct you to is the configure script of the FFmpeg itself that contains the [list of supported flags](https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/refs/heads/release/4.4:/configure#l61).
