### ISSUE TITLE
Problem with building files

### ISSUE THREAD

**Issue by riyaznaz** [Javernaut/ffmpeg-android-maker#68]
Hello guys i am having problem with this clang: error: no such file or directory: 'libavcodec/h2645_par'
make: *** [ffbuild/library.mak:119: libavcodec/libavcodec.so.59] Error 1

**Comment by Javernaut** [comment]
Hello.

Just this one line doesn't tell anything helpful. Could you please post more logs?
As well as the info about your environment (like NDK version).

**Comment by riyaznaz** [comment]
Hello thank you for reply.

ffpmeg version is 5.1,  NDK version is 25.0.8775105

When i use this ./ffmpeg-android-maker.sh command it takes sometime to process the things after end of the process the error is showing given below. 


libswresample/options.c:130:144: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to
      9223372036854775808 [-Wimplicit-const-int-float-conversion]
  ..., OFFSET(firstpts_in_samples), AV_OPT_TYPE_INT64 ,{.i64=AV_NOPTS_VALUE    }, INT64_MIN,INT64_MAX, PARAM },
                                                                                            ^~~~~~~~~
C:/Users/Riyaz/AppData/Local/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/stdint.h:188:27: note:
      expanded from macro 'INT64_MAX'
#define INT64_MAX        (INT64_C(9223372036854775807))
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Riyaz/AppData/Local/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/stdint.h:147:27: note:
      expanded from macro 'INT64_C'
#  define INT64_C(c)      c ## LL
                          ^~~~~~~
<scratch space>:93:1: note: expanded from here
9223372036854775807LL
CC      libswresample/resample.o
^~~~~~~~~~~~~~~~~~~~~
libswresample/options.c:70:145: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to
      9223372036854775808 [-Wimplicit-const-int-float-conversion]
  ...OFFSET(user_out_ch_layout), AV_OPT_TYPE_CHANNEL_LAYOUT, {.i64=0         }, INT64_MIN, INT64_MAX, PARAM|DEPREC, "channel_layout"},  
                                                                                           ^~~~~~~~~
C:/Users/Riyaz/AppData/Local/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/stdint.h:188:27: note:
      expanded from macro 'INT64_MAX'
#define INT64_MAX        (INT64_C(9223372036854775807))
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Riyaz/AppData/Local/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/stdint.h:147:27: note:
      expanded from macro 'INT64_C'
#  define INT64_C(c)      c ## LL
                          ^~~~~~~
<scratch space>:90:1: note: expanded from here
9223372036854775807LL
CC      libswresample/resample_dsp.o
^~~~~~~~~~~~~~~~~~~~~
libswresample/options.c:68:145: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to
      9223372036854775808 [-Wimplicit-const-int-float-conversion]
  ...OFFSET(user_out_ch_layout), AV_OPT_TYPE_CHANNEL_LAYOUT, {.i64=0         }, INT64_MIN, INT64_MAX, PARAM|DEPREC, "channel_layout"},
                                                                                           ^~~~~~~~~
C:/Users/Riyaz/AppData/Local/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/stdint.h:188:27: note:
      expanded from macro 'INT64_MAX'
#define INT64_MAX        (INT64_C(9223372036854775807))
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Riyaz/AppData/Local/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/stdint.h:147:27: note:
      expanded from macro 'INT64_C'CC   libswresample/swresample.o

#  define INT64_C(c)      c ## LL
                          ^~~~~~~
<scratch space>:88:1: note: expanded from here
9223372036854775807LL
^~~~~~~~~~~~~~~~~~~~~
libswresample/options.c:66:145: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to
      9223372036854775808 [-Wimplicit-const-int-float-conversion]
  ...OFFSET(user_in_ch_layout), AV_OPT_TYPE_CHANNEL_LAYOUT, {.i64=0          }, INT64_MIN, INT64_MAX, PARAM|DEPREC, "channel_layout"},
                                                                                           ^~~~~~~~~
C:/Users/Riyaz/AppData/Local/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/stdint.h:188:27:n 
ote:
      expanded from macro 'INT64_MAX'
#define INT64_MAX        (INT64_C(9223372036854775807))
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
CC      libswresample/swresample_frame.o
C:/Users/Riyaz/AppData/Local/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/stdint.h:147:27: note:
      expanded from macro 'INT64_C'
#  define INT64_C(c)      c ## LL
                          ^~~~~~~
<scratch space>:86:1: note: expanded from here
9223372036854775807LL
^~~~~~~~~~~~~~~~~~~~~
libswresample/options.c:64:145: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to
      9223372036854775808 [-Wimplicit-const-int-float-conversion]
  ...OFFSET(user_in_ch_layout), AV_OPT_TYPE_CHANNEL_LAYOUT, {.i64=0          }, INT64_MIN, INT64_MAX, PARAM|DEPREC, "channel_layout"},  
                                                                                           ^~~~~~~~~
C:/Users/Riyaz/AppData/Local/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/stdint.h:188:27: note:
      expanded from macro 'INT64_MAX'
#define INT64_MAX        (INT64_C(9223372036854775807))
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Riyaz/AppData/Local/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/stdint.h:147:27CC
libswresample/version.o
: note: 
      expanded from macro 'INT64_C'
#  define INT64_C(c)      c ## LL
                          ^~~~~~~
<scratch space>:84:1: note: expanded from here
9223372036854775807LL
^~~~~~~~~~~~~~~~~~~~~
5 warnings generated.
CC      libswresample/log2_tab.o
GEN     libavdevice/libavdevice.pc
GEN     libavfilter/libavfilter.pc
GEN     libavformat/libavformat.pc
GEN     libavcodec/libavcodec.pc
GEN     libswresample/libswresample.pc
GEN     libswscale/libswscale.pc
GEN     libavutil/libavutil.pc
HOSTCC  doc/print_options.o
/usr/bin/sh: gcc: command not found
CC      fftools/ffmpeg_filter.o
make: *** [ffbuild/common.mak:201: doc/print_options.o] Error 127
make: *** Waiting for unfinished jobs....
CC      fftools/ffmpeg_hw.o
CC      fftools/ffmpeg_mux.o
GEN     libavdevice/libavdevice.ver
GEN     libavfilter/libavfilter.ver
GEN     libswscale/libswscale.ver
GEN     libavutil/libavutil.ver
LD      libavutil/libavutil.so.57
LD      libswscale/libswscale.so.6
GEN     libavformat/libavformat.ver
GEN     libavcodec/libavcodec.ver
GEN     libswresample/libswresample.ver
LD      libswresample/libswresample.so.4
LD      libavcodec/libavcodec.so.59
clang: error: no such file or directory: 'libavcodec/h2645_par'
make: *** [ffbuild/library.mak:119: libavcodec/libavcodec.so.59] Error 1

**Comment by Javernaut** [comment]
How exactly do you execute the script on Windows? In what terminal/shell? Do you use WSL?
Have you tried [Doker](https://github.com/Javernaut/ffmpeg-android-maker/wiki/Docker-support)?

**Comment by riyaznaz** [comment]
I am git bash to execute the script on my windows

**Comment by Javernaut** [comment]
I know that thing, but I personally didnt test it. Log ago I used MSYS2, now I recommend either WSL2 (and latest Ubuntu installed through that) or usind Doker. Please try one of these opitons.

**Comment by riyaznaz** [comment]
Thank you for your response. 

I will use one of them to execute scripts. thank you so much for saving my time.
