### ISSUE TITLE
How to enable h264_mediacodec for decoding?

### ISSUE THREAD

**Issue by geminixdev** [Javernaut/ffmpeg-android-maker#76]
I built the libraries, but h264_mediacodec is not available, also not for decoding.

```
W Player  : [09 2:25:58.386 CEST W]  None of the hardware accelerations are supported
D Player  : [09 2:25:58.391 CEST D]  Available pixel formats:
D Player  : [09 2:25:58.392 CEST D]     yuv420p : AVPixelFormat( 0 )
D Player  : [09 2:25:58.392 CEST D]  Using software decoding in yuv420p
```
I don't see any option to enable it when running the script. 

How to enable h264_mediacodec for decoding?

**Comment by Javernaut** [comment]
Hello.

The logs are rather meaningless. I can only see that the hardware acceleration doesn't work, but not the decoding per se.

How exactly did you build the library? How do you try to execute it? What produces the logs from above?

Meanwhile I tried to enable the h264_mediacodec with just adding these flags to FFmpeg's configure script:

```
--disable-vulkan \
--enable-mediacodec \
```

Make sure you append -landroid to --extra-ldflags like this:
`--extra-ldflags="$DEP_LD_FLAGS -landroid" \`

And also make sure you didn't disable the pthreads like this:
`--disable-pthreads \`

**Comment by geminixdev** [comment]
> Hello.
> 
> The logs are rather meaningless. I can only see that the hardware acceleration doesn't work, but not the decoding per se.
> 
> How exactly did you build the library? 

Using the script from here without any modification.

./ffmpeg-android-maker.sh --source-tar=5.1.3 -android=23 -abis=armeabi-v7a,arm64-v8a

> How do you try to execute it? What produces the logs from above?

My Custom player built using QtAVPlayer.

> 
> Meanwhile I tried to enable the h264_mediacodec with just adding these flags to FFmpeg's configure script:
> 
> ```
> --enable-jni \
> --enable-mediacodec \
> ```
> 
> Make sure you append -landroid to --extra-ldflags like this: `--extra-ldflags="$DEP_LD_FLAGS -landroid" \`
> 
> And also make sure you didn't disable the pthreads like this: `--disable-pthreads \`

Thanks, I will try that!

**Comment by geminixdev** [comment]
Success, with the changes, as you proposed them, now the ffmepg configure output lists:

Under **External libraries**:
mediacodec

Under **Enabled decoders**:
h264_mediacodec
hevc_mediacodec
mpeg2_mediacodec
mpeg4_mediacodec
vp8_mediacodec
vp9_mediacodec

And when running the player:

```
D Player  : [12 12:47:20.700 CEST D]  FFmpeg: [h264_mediacodec @ 0x7a60fa7640] Output crop parameters top=0 bottom=575 left=0 right=1023, resulting dimensions width=1024 height=576
04-12 12:47:20.700 13253 13608 D Player  :
D Player  : [12 12:47:20.700 CEST D]  FFmpeg: [h264_mediacodec @ 0x7a60fa7640] MediaCodec started successfully: codec = OMX.Exynos.avc.dec, ret = 0
04-12 12:47:20.700 13253 13608 D Player  :
D Player  : [12 12:47:20.700 CEST D]  h264_mediacodec : supported hardware device contexts:
D Player  : [12 12:47:20.700 CEST D]      mediacodec
D Player  : [12 12:47:20.700 CEST D]  Creating hardware device context: mediacodec
D Player  : [12 12:47:20.700 CEST D]  Using hardware device context: mediacodec

```

Thanks!
