### ISSUE TITLE
Ffmpeg.so file for android

### ISSUE THREAD

**Issue by sourav-dey** [Javernaut/ffmpeg-android-maker#80]
Hi,
I see the code produces an android executable for ffmpeg and ffprobe.
Is there a way to produce ffmpeg.so lib?

**Comment by Javernaut** [comment]
Hello,
Not really. FFmpeg as a project is actually a **set** of libraries and you can import them instead. Additionally it has the ffmpeg **binary** and it is just a facade for the same libraries.
