### ISSUE TITLE
Add external library libxml2

### ISSUE THREAD

**Issue by laestrygonian** [Javernaut/ffmpeg-android-maker#86]
Would be nice to add libxml2 support which is needed for dash demuxer in ffmpeg.

Thanks

**Comment by Javernaut** [comment]
Hello @laestrygonian ,

Have you tried integrating the library on your own? I don't thing this particular one is hard to integrate, but I'm rather occupied with other stuff currently.

**Comment by laestrygonian** [comment]
Sure I can try, I will try to post a patch.

**Comment by Javernaut** [comment]
Closing, as #88 is merged
