### ISSUE TITLE
Host compiler lacks C11 support

### ISSUE THREAD

**Issue by Kyant0** [Javernaut/ffmpeg-android-maker#89]
I tried NDK r21 and r25, they both reported:

![image](https://github.com/Javernaut/ffmpeg-android-maker/assets/76829190/d91425fb-479d-4c38-8703-79eecae9bb83)

**Comment by Javernaut** [comment]
Have you tried ndk r26c? GitHub Actions use Linux with this version of ndk and the build is successful. I'll try previous versions of ndk later today.

**Comment by Kyant0** [comment]
Yes, r26c is also broken

**Comment by Kyant0** [comment]
I saw your workflow contains:
-- Check for working C compiler: /usr/local/lib/android/sdk/ndk/26.2.11394342/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped

But mine is linux-x86_64/i686-linux-android21-clang
Besides, I am using WSL on Windows

**Comment by Javernaut** [comment]
Ok, so it is windows with wsl actually. What Linux distribution do you use with it?

Also, have you tried Docker image?

I'll be able to check the wsl tomorrow I guess

**Comment by Kyant0** [comment]
The default Ubuntu

**Comment by Javernaut** [comment]
Can you also share your sources/ffmpeg/ffmpeg-7.0/ffbuild/config.log file? Or at least its end part. Usually one can find valuable info there.

**Comment by Javernaut** [comment]
So, I managed to access my Windows machine much earlier. I successfully compiled the vanilla FFmpeg (without any external libs), so I assume it is something wrong with the configuration of your machine.

My setup:
- Windows 11
- WSL2
- Ubuntu 22.04
- Android NDK both r25c and r26c

Did you install exactly the Linux versions of both Android SDK and NDK into your Linux subsystem?

And the sources/ffmpeg/ffmpeg-7.0/ffbuild/config.log file is really helpful for this kind of problems. Please, share it or the end part of it.

As for your comment:
> I saw your workflow contains:
> -- Check for working C compiler: /usr/local/lib/android/sdk/ndk/26.2.11394342/toolchains/llvm/prebuilt/linux-> x86_64/bin/clang - skipped
>
> But mine is .../linux-x86_64/bin/i686-linux-android21-clang

There is nothing wrong here. There is only one compiler in NDK actually, which is just `clang`. All other files like `i686-linux-android21-clang` just call `clang` under the hood and pass additional arguments.
<img width="691" alt="Screenshot 2024-04-06 at 19 31 47" src="https://github.com/Javernaut/ffmpeg-android-maker/assets/979018/fc9f2add-593d-415d-94d9-185f7abce3e3">

**Comment by Kyant0** [comment]
Always thanks for your timely reply and hard work 😁, good job then.
