### ISSUE TITLE
x265 build is broken.

### ISSUE THREAD

**Issue by cryptrr** [Javernaut/ffmpeg-android-maker#99]
There's an issue with path for the x265 lib build.

**Comment by cryptrr** [comment]
https://github.com/Javernaut/ffmpeg-android-maker/pull/100

**Comment by Javernaut** [comment]
Have you tried the current development branch? Is the issue reproducible there as well?

**Comment by Javernaut** [comment]
The libx265 actually works fine in current development branch.
